# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: mnist.yaml
  - transforms: mnist.yaml
  - model: mnist.yaml
  - callbacks: default.yaml
  - logger: default.yaml
  - trainer: default.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
  # - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# seed for random number generators in pytorch, numpy and python.random
seed: 0

# name for the clearml tracking (you can overwrite this name in experiment configs)
project_name: null
task_name: null

# not to change workdir
hydra:
  run:
    dir: ./
  output_subdir: ${data_dir}
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        # absolute file path
        # filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
        filename: ${original_work_dir}/logs/${hydra.job.name}.log
    root:
      level: INFO
      handlers: [console, file]

    disable_existing_loggers: false
