name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - '**/main'
      - develop
      - '**/develop'

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python PYTHONVERSION
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools pytest
        pip install -r requirements.txt
        if [ -f requirements/sample-requirements.txt ]; then pip install -r requirements/sample-requirements.txt; fi
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --select=E9,F63,F7,F82 --show-source --max-complexity=10 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests --doctest-modules my_package